
  server:
    port: 8083 #${PORT:0}
  spring:
    application:
      name: service-creditCard
    main:
      allow-bean-definition-overriding: true
    data:
      mongodb:
        uri: mongodb://localhost:27017
        database: creditCard

  eureka:
    client:
    service-url:
    defaultZone: http://localhost:8761/eureka

